# Generated by Django 2.0.6 on 2018-07-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRegra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacao', models.CharField(choices=[('FROM', 'Remetente'), ('TO', 'Destinatário'), ('CC', 'Destinatário em cópia')], max_length=4)),
                ('conteudo', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_pesquisar', models.CharField(default='INBOX', max_length=250)),
                ('pasta_destino', models.CharField(max_length=250)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imapfilter.Email')),
            ],
        ),
        migrations.AddField(
            model_name='itemregra',
            name='regra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imapfilter.Regra'),
        ),
    ]
